package concepts;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;

public class ValueFormattingInJava {

    /**
     * Often, while attempting coding interview questions it is observed it is required to
     * round off values to a certain number of places, in order to clean the output generated by
     * the problem statement.
     * The below techniques will help to round of a double value to certain number of places.
     * */
    public static void main(String[] args) {
        /*
         * Math.round():
         * The Math.round() method is part of the java.lang.Math class and is used
         * for rounding a floating-point number to the nearest integer.
         * It uses the standard rounding rules, rounding to the nearest integer with ties rounding to the
         * nearest even number (also known as "round half to even" or "banker's rounding").
        * */
        double num = 3.76587976657;
        long roundedNum = Math.round(num); // Output = 4.0

        /*
        *  Math.floor():
        *  The Math.floor() method returns the largest integer less than or equal to a given number.
        *  It effectively rounds down to the nearest integer. For example:
        *
        **/
        double roundedNumDouble = Math.floor(num); // Output = 3.0

        /*
         * DecimalFormat:
         *  You can also use the DecimalFormat class to format and round decimal numbers according to a specified pattern.
         *  This provides more control over the rounding and formatting process. Here's an example.
         * */
        DecimalFormat decimalFormat = new DecimalFormat("#.####");
        String formatted = decimalFormat.format(num); // Output: 3.7659
        // String can be converted to double, Long, Float using parseDouble, parseLong, parseFloat respectively.

        /*
        * BigDecimal:
        * When you need precise decimal arithmetic and control over rounding, especially in financial applications, you can use the BigDecimal class.
        * You can specify the rounding mode and the number of decimal places to round to using the setScale method. For example:
        **/
        BigDecimal bigDecimal = new BigDecimal(num);
        BigDecimal roundedNumBig = bigDecimal.setScale(4, RoundingMode.HALF_UP);
        double val = roundedNumBig.doubleValue();
    }
}
